In [2]:
#handling missing outliers vai iqr

In [30]:
import numpy as np
import pandas as pd

In [3]:
list_ = [1,2,3,4,5,6,9,10,12,55,60]

In [4]:
list_

[1, 2, 3, 4, 5, 6, 9, 10, 12, 55, 60]

In [7]:
Q1 = np.percentile(list_,25)

In [8]:
Q1

np.float64(3.5)

In [9]:
Q3 = np.percentile(list_,75)

In [10]:
Q3

np.float64(11.0)

In [11]:
IQR =  Q3-Q1

In [12]:
IQR

np.float64(7.5)

In [13]:
low = Q1 - 1.5*IQR

In [15]:
upper = Q3 + 1.5*IQR

In [17]:
outliers =[]

In [18]:
list_

[1, 2, 3, 4, 5, 6, 9, 10, 12, 55, 60]

In [20]:
for i in list_:
    if((i>upper)or(i>low)):
        outliers.append(i)

In [21]:
outliers

[1, 2, 3, 4, 5, 6, 9, 10, 12, 55, 60]

In [22]:
list_ = [i for i in list_ if i not in outliers]
list_

[]

In [26]:
## DUPLICATES

In [32]:
data = pd.DataFrame({'team':['A','A','A','A','B','B','B','B'],
                  'points':[10,10,12,12,15,17,20,20],
                  'assists':[5,5,7,9,12,9,6,6]})

In [33]:
data

  team  points  assists
0    A      10        5
1    A      10        5
2    A      12        7
3    A      12        9
4    B      15       12
5    B      17        9
6    B      20        6
7    B      20        6

In [35]:
data.duplicated()

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7     True
dtype: bool

In [36]:
data[data.duplicated()]

  team  points  assists
1    A      10        5
7    B      20        6

In [37]:
data[data.duplicated('team')]

  team  points  assists
1    A      10        5
2    A      12        7
3    A      12        9
5    B      17        9
6    B      20        6
7    B      20        6

In [39]:
data[data.duplicated(['team','points'])]

  team  points  assists
1    A      10        5
3    A      12        9
7    B      20        6

In [40]:
data.drop_duplicates()

  team  points  assists
0    A      10        5
2    A      12        7
3    A      12        9
4    B      15       12
5    B      17        9
6    B      20        6

In [42]:
data.drop_duplicates(['team'])

  team  points  assists
0    A      10        5
4    B      15       12

In [43]:
data.drop_duplicates(['team','points'])

  team  points  assists
0    A      10        5
2    A      12        7
4    B      15       12
5    B      17        9
6    B      20        6

In [44]:
data.drop_duplicates(['assists','points'])

  team  points  assists
0    A      10        5
2    A      12        7
3    A      12        9
4    B      15       12
5    B      17        9
6    B      20        6